### PR TITLE
Add citation for IROS paper

### PR DESCRIPTION
**Pull request by SteveMacenski**

### CODE REVIEW

**Comment by SteveMacenski** [comment]
CC @ruffsl

**Comment by SteveMacenski** [comment]
https://214-240847415-gh.circle-artifacts.com/0/html/index.html

Here's the CI rendering, look good to you to merge?

**Comment by ruffsl** [comment]
May want to add a MLA snippet and links to archive and repo in bibtex. We'll want to also add the DOI once it comes out.

https://github.com/ros-planning/navigation2/pull/1867

**Comment by SteveMacenski** [comment]
@ruffsl you mean the "S. Macenski, F. Martín, R. White, J. Clavero. The Marathon 2: A Navigation System. IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2020." line above the latex?

**Comment by ruffsl** [comment]
Yep, but with the title as a clickable hyperlink to quickly and freely read the publication.

**Pull request merged**
