### PR TITLE
docs added for single trigger

### PR DESCRIPTION
**Pull request by padhupradheep**
Even ``IsStuck`` BT node does not have a child. 

Also the note given in the main BT configuration page does not explain what it does.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
CI failed

**Comment by padhupradheep** [comment]
Actually #294 also failed for some reason. Let me check.

**Comment by SteveMacenski** [comment]
Maybe: https://github.com/readthedocs/readthedocs.org/issues/9037 helps?

**Comment by padhupradheep** [comment]
That works, sorry for the late update, was away for the weekend...

Check #296

**Comment by SteveMacenski** [comment]
Rebase so it builds and then can merge!

**Comment by SteveMacenski** [comment]
Thanks! I freckin' love more documentation

**Pull request closed without merging**
