### PR TITLE
adding costmaps param descriptions

### PR DESCRIPTION
**Pull request by SteveMacenski**
#21 

@Marwan99 do you think I should separate these onto multiple pages or just 1 big page?

(feels good to be done with this haha)

### CODE REVIEW

**Comment by Marwan99** [comment]
I reckon splitting is probably better.

**Comment by SteveMacenski** [comment]
OK I split them up

**Comment by SteveMacenski** [comment]
thoughts @Marwan99 ?

**Comment by Marwan99** [comment]
LGTM.

You can get rid of the space between "``<obstacle layer>``. ``<data source>``" by changing it "``<obstacle layer>``.\ ``<data source>``"

**Comment by SteveMacenski** [comment]
Oh and now CI randomly starts to show up on the repo? that's some weird behavior, circle ci.

**Pull request merged**
